<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>SENSS</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/cytoscape.min.js"></script>
    <script src="js/jquery.qtip.min.js"></script>
    <link rel="stylesheet" href="css/jquery.qtip.min.css">
    <script src="js/cytoscape-qtip.js"></script>
    <style>
        .panel {
            width: 300px;
            margin: auto;
            padding: 30px;
        }

        .panel-offset-senss {
            margin: auto;
        }

        .second-button {
            float: right;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="direct_floods_form.php">SENSS</a>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li><a href="direct_floods_form.php">Direct Floods</a></li>
            </ul>
        </div>
    </div>
</nav>
<body>
<!-- This is the image which is generated by the python script which monitors the entire topology
<img src="demo_proxy.png" width="100%" height="100%"> -->

<div id="network-canvas" style="height: 500px; width: 1080px; margin: 0 auto; border: 1px solid black;"></div>

<div class="container inner-container">
    <div class="col-md-8">
        <h2>
            Monitoring Table
        </h2>
    </div>
    <div class="col-md-4">
        Threshold: <span id="current-threshold"></span>&emsp;
        <button class="btn btn-primary" id="set-threshold">
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
        </button>
    </div>
    <div class="col-md-8">
        <p>Monitor traffic and add/remove rules</p>
    </div>
    <div class="col-md-4">
        <p>
            <button type="button" class="btn btn-default" id="add-monitoring-rule">Add Monitoring Rule</button>
        </p>
    </div>
    <table id="table-monitor" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>AS Name</th>
            <th>Match</th>
            <th>Packet Count</th>
            <th>Byte Count</th>
            <th>Speed</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<div id="set-threshold-modal" class="modal fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Set Threshold</h4>
            </div>
            <div class="modal-body" style="height:200px;">
                <table class="table">
                    <tr>
                        <td><input type="text" class="form-control" id="threshold-value"></td>
                        <td>
                            <div class="dropdown">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                    <span id="selected">Select rate</span><span class="caret"></span></button>
                                <ul class="dropdown-menu" id="threshold-rate">
                                    <li><a href="#">KBps</a></li>
                                    <li><a href="#">MBps</a></li>
                                    <li><a href="#">GBps</a></li>
                                    <li><a href="#">TBps</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="modal-footer">
                <div id="set-threshold-button" class="btn btn-success">Set Threshold</div>
            </div>
        </div>
    </div>
</div>

<div id="add-monitor-modal" class="modal fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Add Monitoring Rule</h4>
            </div>
            <div class="modal-body">
                <table class="table">
                    <tr>
                        <th>
                            <label for="as_name">AS Name:</label>
                        </th>
                        <td>
                            <select id="as_name" class="multiselect-ui form-control" multiple="multiple">

                            </select>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="nw_src">Source IP:</label>
                        </th>
                        <td>
                            <input type="text" id="nw_src" class="form-control">
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="nw_dst">Destination IP:</label>
                        </th>
                        <td>
                            <input type="text" id="nw_dst" class="form-control">
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="tcp_src">TCP Source Port:</label>
                        </th>
                        <td>
                            <input type="text" id="tcp_src" class="form-control">
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="tcp_dst">TCP Destination Port:</label>
                        </th>
                        <td>
                            <input type="text" id="tcp_dst" class="form-control">
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="udp_src">UDP Source Port:</label>
                        </th>
                        <td>
                            <input type="text" id="udp_src" class="form-control">
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="udp_dst">UDP Destination Port:</label>
                        </th>
                        <td>
                            <input type="text" id="udp_dst" class="form-control">
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="monitor_freq">Monitoring Frequency</label>
                        </th>
                        <td>
                            <input type="text" id="monitor_freq" class="form-control">
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <label for="monitor_duration">Monitoring Duration</label>
                        </th>
                        <td>
                            <input type="text" id="monitor_duration" class="form-control">
                        </td>
                    </tr>
                </table>
            </div>

            <div class="modal-footer">
                <div id="add-monitor-rule" class="btn btn-success">Add Monitoring Rule</div>
            </div>
        </div>
    </div>
</div>
<?php
$servername = "localhost";
$username = "root";
$password = "sitscomp";
$dbname = "SENSS";
$conn = new mysqli($servername, $username, $password, $dbname);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
//We monitor the database to see if there are updates to the stats
//Stats are filled by the python script which monitors
$sql = "SELECT * FROM DIRECT_FLOODS";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        //This is SENSS PROXY - when the SENSS servers are not reachable we hand over the control
        $proxy = $row["PROXY"];
        if ($proxy == "1") {
            echo '<div class="alert alert-danger">';
            echo '<strong>SENSS Servers unreachable!</strong> <a href="http://localhost:8181/direct_floods_multiple_view_proxy.php">Go to Proxy</a>';
            echo '</div>';
        }
        $attack = $row["ATTACK"];
        if ($proxy == "0" && $attack == "1") {
            echo '<div class="alert alert-danger">';
            $attack_from = $row["ATTACK_FROM"];
            echo '<strong>Info:</strong> Attack traffic from ' . $attack_from;
            echo '</div>';
            echo '<div class="alert alert-info">';
            echo '<strong>Info:</strong> Request SENSS ISP to add filters below.';
            echo '</div>';
        }
        if ($proxy == "0" && $attack == "0") {
            echo '<div class="alert alert-info">';
            echo '<strong>Info:</strong> SENSS ISP at ARNEP,EQUINIX and INTERNEXA';
            echo '</div>';
            echo '<div class="alert alert-info">';
            echo '<strong>Info:</strong> Legit traffic from UEM,AMTI and ENTEL';
            echo '</div>';
        }
        $result = json_decode($row["RESULT"], true);
        echo '<table  class="table table-striped" align="center" style="width: auto;">';
        echo '<tr><th>DPID</th><th>Action</th><th>Stop Action</th></tr>';
        //We obtain the Stats
        //Stats are grouped by the switch DPID. In our case the DPID will the SENSS controller at multiple points
        foreach ($result as $dpid => $count) {
            $dpid_of_switch = $count["DPID"];
            $isp_of_switch = $count["ISP"];
            $filter = explode(",", $row["FILTER"]);
            $remove_action = false;
            foreach ($filter as $filter_dpid) {
                if ($filter_dpid == $dpid_of_switch) {
                    $remove_action = true;
                }
            }
            //Mark tells us if we are under an attack or not. This enables the network operator to add rules
            if ($count["Mark"] == "True" and $proxy == "0") {
                //This condition checks if there is already a rule by the network operator
                //If there is a rule, then we need to give an option to remove the rule and call the remove_filter.php to remove the filter
                if ($remove_action == true) {
                    echo '<tr><td>' . $isp_of_switch . '</td><td></td><td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#Remove-' . $dpid . '">Remove Filter</button></td></tr>';
                    echo '<div id="Remove-' . $dpid . '" class="modal fade" role="dialog">';
                    echo '<div class="modal-dialog">';
                    echo '<div class="modal-content">';
                    echo '<div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button>';
                    echo '<h4 class="modal-title">Remove Filter</h4>';
                    echo '</div>';
                    echo '<div class="modal-body">';
                    echo '<form name="remove_filter_form" id="remove_filter_form" action="remove_filter.php" method="post">';
                    echo '<h3> Are you sure you want to remove this filter?</h3>';
                    echo '<input type="hidden" name="request_id" value="' . $row["ID"] . '"/>';
                    echo '<input type="hidden" name="dpid" value="' . $dpid_of_switch . '"/>';

                    echo '<input type="submit" class="btn" name="formSubmit" value="Submit"/> ';
                    echo '</form> ';
                    echo '</div>';
                    echo '</div>';
                    echo '</div>';
                    echo '</div>';
                }
                //Else if there is no rule, we call the modal to add the filter. This is where the network operator add the MATCH fields
                //After the form is filled, the contents are transferred to add_filter.php which adds the filters
                else {
                    echo '<tr><td>' . $isp_of_switch . '</td>' . '<td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#Add-' . $dpid . '">Add Filter</button></td><td></td></tr>';
                }
                //This is the modal for adding rule
                echo '<div id="Add-' . $dpid . '" class="modal fade" role="dialog">';
                echo '<div class="modal-dialog">';
                echo '<div class="modal-content">';
                echo '<div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button>';
                echo '<h4 class="modal-title">Add Filter</h4>';
                echo '</div>';
                echo '<div class="modal-body">';
                echo '<form name="add_filter_form" id="add_filter_form" action="add_filter.php" method="post">';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="dpid" id="dpid" maxlength="50"  readonly="readonly" value="' . $dpid_of_switch . '" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="nw_src" id="nw_src" maxlength="50"  placeholder="Source IP" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="nw_dst" id="nw_dst" maxlength="50"  placeholder="Destination IP" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="in_port" id="in_port" maxlength="50"  placeholder="In Port" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="eth_dst" id="eth_dst" maxlength="50"  placeholder="Destination MAC" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="eth_src" id="eth_src" maxlength="50"  placeholder="Source MAC" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="dl_vlan" id="dl_vlan" maxlength="50"  placeholder="VLAN ID" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="tcp_src" id="tcp_src" maxlength="50"  placeholder="TCP Source Port" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="tcp_dst" id="tcp_dst" maxlength="50"  placeholder="TCP Destination Port" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="udp_src" id="udp_src" maxlength="50"  placeholder="UDP Source Port" />';
                echo '</div>';
                echo '<div class="form-group">';
                echo '<input type="text" style="width:200px;" class="form-control" name="udp_dst" id="udp_dst" maxlength="50"  placeholder="UDP Destination Port" />';
                echo '</div>';
                echo '<input type="hidden" name="request_id" value="' . $row["ID"] . '"/>';
                echo '<input type="submit" class="btn" name="formSubmit" value="Submit"/> ';
                echo '</form> ';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
            } else {
                //"Mark" is false
                //and we want to remove the filter if there is filter.
                //This is to remove rules when the attacks are over
                if ($remove_action == true) {
                    echo '<tr><td>' . $isp_of_switch . '</td><td></td><td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#Remove-' . $dpid . '">Remove Filter</button></td></tr>';
                    echo '<div id="Remove-' . $dpid . '" class="modal fade" role="dialog">';
                    echo '<div class="modal-dialog">';
                    echo '<div class="modal-content">';
                    echo '<div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button>';
                    echo '<h4 class="modal-title">Add Filter</h4>';
                    echo '</div>';
                    echo '<div class="modal-body">';
                    echo '<form name="remove_filter_form" id="remove_filter_form" action="remove_filter.php" method="post">';
                    echo '<h3> Are you sure you want to remove this filter?</h3>';
                    echo '<input type="hidden" name="request_id" value="' . $row["ID"] . '"/>';
                    echo '<input type="hidden" name="dpid" value="' . $dpid_of_switch . '"/>';
                    echo '<input type="submit" class="btn" name="formSubmit" value="Submit"/> ';
                    echo '</form> ';
                    echo '</div>';
                    echo '</div>';
                    echo '</div>';
                    echo '</div>';
                } //"Mark" is false and there are no rules. So it just displays the SENSS ISPs
                else {
                    echo '<tr><td>' . $isp_of_switch . '</td><td></td><td></td></tr>';
                }
            }
        }
    }
}
?>
</body>
<script src="js/render_network.js"></script>
<script src="js/script.js"></script>
</html>
