// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

#ifndef PROTOBUF_map_2eproto__INCLUDED
#define PROTOBUF_map_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace Collector {
class Cell;
class CellDefaultTypeInternal;
extern CellDefaultTypeInternal _Cell_default_instance_;
class FlowKeyValue;
class FlowKeyValueDefaultTypeInternal;
extern FlowKeyValueDefaultTypeInternal _FlowKeyValue_default_instance_;
class FlowStats;
class FlowStatsDefaultTypeInternal;
extern FlowStatsDefaultTypeInternal _FlowStats_default_instance_;
class IpRange;
class IpRangeDefaultTypeInternal;
extern IpRangeDefaultTypeInternal _IpRange_default_instance_;
class Record;
class RecordDefaultTypeInternal;
extern RecordDefaultTypeInternal _Record_default_instance_;
class Record_RecordElemEntry;
class Record_RecordElemEntryDefaultTypeInternal;
extern Record_RecordElemEntryDefaultTypeInternal _Record_RecordElemEntry_default_instance_;
class Vector;
class VectorDefaultTypeInternal;
extern VectorDefaultTypeInternal _Vector_default_instance_;
}  // namespace Collector

namespace Collector {

namespace protobuf_map_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_map_2eproto

// ===================================================================

class FlowStats : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Collector.FlowStats) */ {
 public:
  FlowStats();
  virtual ~FlowStats();

  FlowStats(const FlowStats& from);

  inline FlowStats& operator=(const FlowStats& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FlowStats& default_instance();

  static inline const FlowStats* internal_default_instance() {
    return reinterpret_cast<const FlowStats*>(
               &_FlowStats_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(FlowStats* other);

  // implements Message ----------------------------------------------

  inline FlowStats* New() const PROTOBUF_FINAL { return New(NULL); }

  FlowStats* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FlowStats& from);
  void MergeFrom(const FlowStats& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FlowStats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Collector.FlowKeyValue entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::Collector::FlowKeyValue& entries(int index) const;
  ::Collector::FlowKeyValue* mutable_entries(int index);
  ::Collector::FlowKeyValue* add_entries();
  ::google::protobuf::RepeatedPtrField< ::Collector::FlowKeyValue >*
      mutable_entries();
  const ::google::protobuf::RepeatedPtrField< ::Collector::FlowKeyValue >&
      entries() const;

  // @@protoc_insertion_point(class_scope:Collector.FlowStats)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Collector::FlowKeyValue > entries_;
  mutable int _cached_size_;
  friend struct protobuf_map_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FlowKeyValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Collector.FlowKeyValue) */ {
 public:
  FlowKeyValue();
  virtual ~FlowKeyValue();

  FlowKeyValue(const FlowKeyValue& from);

  inline FlowKeyValue& operator=(const FlowKeyValue& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FlowKeyValue& default_instance();

  static inline const FlowKeyValue* internal_default_instance() {
    return reinterpret_cast<const FlowKeyValue*>(
               &_FlowKeyValue_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(FlowKeyValue* other);

  // implements Message ----------------------------------------------

  inline FlowKeyValue* New() const PROTOBUF_FINAL { return New(NULL); }

  FlowKeyValue* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FlowKeyValue& from);
  void MergeFrom(const FlowKeyValue& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FlowKeyValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Collector.IpRange key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::Collector::IpRange& key() const;
  ::Collector::IpRange* mutable_key();
  ::Collector::IpRange* release_key();
  void set_allocated_key(::Collector::IpRange* key);

  // .Collector.Vector value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::Collector::Vector& value() const;
  ::Collector::Vector* mutable_value();
  ::Collector::Vector* release_value();
  void set_allocated_value(::Collector::Vector* value);

  // @@protoc_insertion_point(class_scope:Collector.FlowKeyValue)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::Collector::IpRange* key_;
  ::Collector::Vector* value_;
  mutable int _cached_size_;
  friend struct protobuf_map_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IpRange : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Collector.IpRange) */ {
 public:
  IpRange();
  virtual ~IpRange();

  IpRange(const IpRange& from);

  inline IpRange& operator=(const IpRange& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IpRange& default_instance();

  static inline const IpRange* internal_default_instance() {
    return reinterpret_cast<const IpRange*>(
               &_IpRange_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(IpRange* other);

  // implements Message ----------------------------------------------

  inline IpRange* New() const PROTOBUF_FINAL { return New(NULL); }

  IpRange* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const IpRange& from);
  void MergeFrom(const IpRange& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(IpRange* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 min = 1;
  void clear_min();
  static const int kMinFieldNumber = 1;
  ::google::protobuf::uint32 min() const;
  void set_min(::google::protobuf::uint32 value);

  // uint32 max = 2;
  void clear_max();
  static const int kMaxFieldNumber = 2;
  ::google::protobuf::uint32 max() const;
  void set_max(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Collector.IpRange)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 min_;
  ::google::protobuf::uint32 max_;
  mutable int _cached_size_;
  friend struct protobuf_map_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Collector.Vector) */ {
 public:
  Vector();
  virtual ~Vector();

  Vector(const Vector& from);

  inline Vector& operator=(const Vector& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector& default_instance();

  static inline const Vector* internal_default_instance() {
    return reinterpret_cast<const Vector*>(
               &_Vector_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Vector* other);

  // implements Message ----------------------------------------------

  inline Vector* New() const PROTOBUF_FINAL { return New(NULL); }

  Vector* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vector& from);
  void MergeFrom(const Vector& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vector* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Collector.Record record = 1;
  int record_size() const;
  void clear_record();
  static const int kRecordFieldNumber = 1;
  const ::Collector::Record& record(int index) const;
  ::Collector::Record* mutable_record(int index);
  ::Collector::Record* add_record();
  ::google::protobuf::RepeatedPtrField< ::Collector::Record >*
      mutable_record();
  const ::google::protobuf::RepeatedPtrField< ::Collector::Record >&
      record() const;

  // @@protoc_insertion_point(class_scope:Collector.Vector)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Collector::Record > record_;
  mutable int _cached_size_;
  friend struct protobuf_map_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class Record : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Collector.Record) */ {
 public:
  Record();
  virtual ~Record();

  Record(const Record& from);

  inline Record& operator=(const Record& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Record& default_instance();

  static inline const Record* internal_default_instance() {
    return reinterpret_cast<const Record*>(
               &_Record_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Record* other);

  // implements Message ----------------------------------------------

  inline Record* New() const PROTOBUF_FINAL { return New(NULL); }

  Record* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Record& from);
  void MergeFrom(const Record& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Record* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .Collector.Cell> record_elem = 1;
  int record_elem_size() const;
  void clear_record_elem();
  static const int kRecordElemFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::Collector::Cell >&
      record_elem() const;
  ::google::protobuf::Map< ::std::string, ::Collector::Cell >*
      mutable_record_elem();

  // @@protoc_insertion_point(class_scope:Collector.Record)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class Record_RecordElemEntry : public ::google::protobuf::internal::MapEntry<Record_RecordElemEntry, 
      ::std::string, ::Collector::Cell,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<Record_RecordElemEntry, 
      ::std::string, ::Collector::Cell,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > SuperType;
    Record_RecordElemEntry();
    Record_RecordElemEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const Record_RecordElemEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_Record_RecordElemEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      Record_RecordElemEntry,
      ::std::string, ::Collector::Cell,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > record_elem_;
  private:
  mutable int _cached_size_;
  friend struct protobuf_map_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Cell : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Collector.Cell) */ {
 public:
  Cell();
  virtual ~Cell();

  Cell(const Cell& from);

  inline Cell& operator=(const Cell& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Cell& default_instance();

  static inline const Cell* internal_default_instance() {
    return reinterpret_cast<const Cell*>(
               &_Cell_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(Cell* other);

  // implements Message ----------------------------------------------

  inline Cell* New() const PROTOBUF_FINAL { return New(NULL); }

  Cell* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Cell& from);
  void MergeFrom(const Cell& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Cell* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string output = 1;
  int output_size() const;
  void clear_output();
  static const int kOutputFieldNumber = 1;
  const ::std::string& output(int index) const;
  ::std::string* mutable_output(int index);
  void set_output(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_output(int index, ::std::string&& value);
  #endif
  void set_output(int index, const char* value);
  void set_output(int index, const char* value, size_t size);
  ::std::string* add_output();
  void add_output(const ::std::string& value);
  #if LANG_CXX11
  void add_output(::std::string&& value);
  #endif
  void add_output(const char* value);
  void add_output(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& output() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_output();

  // repeated double data = 4 [packed = true];
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 4;
  double data(int index) const;
  void set_data(int index, double value);
  void add_data(double value);
  const ::google::protobuf::RepeatedField< double >&
      data() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_data();

  // int32 rows = 2;
  void clear_rows();
  static const int kRowsFieldNumber = 2;
  ::google::protobuf::int32 rows() const;
  void set_rows(::google::protobuf::int32 value);

  // int32 cols = 3;
  void clear_cols();
  static const int kColsFieldNumber = 3;
  ::google::protobuf::int32 cols() const;
  void set_cols(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Collector.Cell)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> output_;
  ::google::protobuf::RepeatedField< double > data_;
  mutable int _data_cached_byte_size_;
  ::google::protobuf::int32 rows_;
  ::google::protobuf::int32 cols_;
  mutable int _cached_size_;
  friend struct protobuf_map_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// FlowStats

// repeated .Collector.FlowKeyValue entries = 1;
inline int FlowStats::entries_size() const {
  return entries_.size();
}
inline void FlowStats::clear_entries() {
  entries_.Clear();
}
inline const ::Collector::FlowKeyValue& FlowStats::entries(int index) const {
  // @@protoc_insertion_point(field_get:Collector.FlowStats.entries)
  return entries_.Get(index);
}
inline ::Collector::FlowKeyValue* FlowStats::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:Collector.FlowStats.entries)
  return entries_.Mutable(index);
}
inline ::Collector::FlowKeyValue* FlowStats::add_entries() {
  // @@protoc_insertion_point(field_add:Collector.FlowStats.entries)
  return entries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Collector::FlowKeyValue >*
FlowStats::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:Collector.FlowStats.entries)
  return &entries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Collector::FlowKeyValue >&
FlowStats::entries() const {
  // @@protoc_insertion_point(field_list:Collector.FlowStats.entries)
  return entries_;
}

// -------------------------------------------------------------------

// FlowKeyValue

// .Collector.IpRange key = 1;
inline bool FlowKeyValue::has_key() const {
  return this != internal_default_instance() && key_ != NULL;
}
inline void FlowKeyValue::clear_key() {
  if (GetArenaNoVirtual() == NULL && key_ != NULL) delete key_;
  key_ = NULL;
}
inline const ::Collector::IpRange& FlowKeyValue::key() const {
  // @@protoc_insertion_point(field_get:Collector.FlowKeyValue.key)
  return key_ != NULL ? *key_
                         : *::Collector::IpRange::internal_default_instance();
}
inline ::Collector::IpRange* FlowKeyValue::mutable_key() {
  
  if (key_ == NULL) {
    key_ = new ::Collector::IpRange;
  }
  // @@protoc_insertion_point(field_mutable:Collector.FlowKeyValue.key)
  return key_;
}
inline ::Collector::IpRange* FlowKeyValue::release_key() {
  // @@protoc_insertion_point(field_release:Collector.FlowKeyValue.key)
  
  ::Collector::IpRange* temp = key_;
  key_ = NULL;
  return temp;
}
inline void FlowKeyValue::set_allocated_key(::Collector::IpRange* key) {
  delete key_;
  key_ = key;
  if (key) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Collector.FlowKeyValue.key)
}

// .Collector.Vector value = 2;
inline bool FlowKeyValue::has_value() const {
  return this != internal_default_instance() && value_ != NULL;
}
inline void FlowKeyValue::clear_value() {
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}
inline const ::Collector::Vector& FlowKeyValue::value() const {
  // @@protoc_insertion_point(field_get:Collector.FlowKeyValue.value)
  return value_ != NULL ? *value_
                         : *::Collector::Vector::internal_default_instance();
}
inline ::Collector::Vector* FlowKeyValue::mutable_value() {
  
  if (value_ == NULL) {
    value_ = new ::Collector::Vector;
  }
  // @@protoc_insertion_point(field_mutable:Collector.FlowKeyValue.value)
  return value_;
}
inline ::Collector::Vector* FlowKeyValue::release_value() {
  // @@protoc_insertion_point(field_release:Collector.FlowKeyValue.value)
  
  ::Collector::Vector* temp = value_;
  value_ = NULL;
  return temp;
}
inline void FlowKeyValue::set_allocated_value(::Collector::Vector* value) {
  delete value_;
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Collector.FlowKeyValue.value)
}

// -------------------------------------------------------------------

// IpRange

// uint32 min = 1;
inline void IpRange::clear_min() {
  min_ = 0u;
}
inline ::google::protobuf::uint32 IpRange::min() const {
  // @@protoc_insertion_point(field_get:Collector.IpRange.min)
  return min_;
}
inline void IpRange::set_min(::google::protobuf::uint32 value) {
  
  min_ = value;
  // @@protoc_insertion_point(field_set:Collector.IpRange.min)
}

// uint32 max = 2;
inline void IpRange::clear_max() {
  max_ = 0u;
}
inline ::google::protobuf::uint32 IpRange::max() const {
  // @@protoc_insertion_point(field_get:Collector.IpRange.max)
  return max_;
}
inline void IpRange::set_max(::google::protobuf::uint32 value) {
  
  max_ = value;
  // @@protoc_insertion_point(field_set:Collector.IpRange.max)
}

// -------------------------------------------------------------------

// Vector

// repeated .Collector.Record record = 1;
inline int Vector::record_size() const {
  return record_.size();
}
inline void Vector::clear_record() {
  record_.Clear();
}
inline const ::Collector::Record& Vector::record(int index) const {
  // @@protoc_insertion_point(field_get:Collector.Vector.record)
  return record_.Get(index);
}
inline ::Collector::Record* Vector::mutable_record(int index) {
  // @@protoc_insertion_point(field_mutable:Collector.Vector.record)
  return record_.Mutable(index);
}
inline ::Collector::Record* Vector::add_record() {
  // @@protoc_insertion_point(field_add:Collector.Vector.record)
  return record_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Collector::Record >*
Vector::mutable_record() {
  // @@protoc_insertion_point(field_mutable_list:Collector.Vector.record)
  return &record_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Collector::Record >&
Vector::record() const {
  // @@protoc_insertion_point(field_list:Collector.Vector.record)
  return record_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Record

// map<string, .Collector.Cell> record_elem = 1;
inline int Record::record_elem_size() const {
  return record_elem_.size();
}
inline void Record::clear_record_elem() {
  record_elem_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::Collector::Cell >&
Record::record_elem() const {
  // @@protoc_insertion_point(field_map:Collector.Record.record_elem)
  return record_elem_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::Collector::Cell >*
Record::mutable_record_elem() {
  // @@protoc_insertion_point(field_mutable_map:Collector.Record.record_elem)
  return record_elem_.MutableMap();
}

// -------------------------------------------------------------------

// Cell

// int32 rows = 2;
inline void Cell::clear_rows() {
  rows_ = 0;
}
inline ::google::protobuf::int32 Cell::rows() const {
  // @@protoc_insertion_point(field_get:Collector.Cell.rows)
  return rows_;
}
inline void Cell::set_rows(::google::protobuf::int32 value) {
  
  rows_ = value;
  // @@protoc_insertion_point(field_set:Collector.Cell.rows)
}

// int32 cols = 3;
inline void Cell::clear_cols() {
  cols_ = 0;
}
inline ::google::protobuf::int32 Cell::cols() const {
  // @@protoc_insertion_point(field_get:Collector.Cell.cols)
  return cols_;
}
inline void Cell::set_cols(::google::protobuf::int32 value) {
  
  cols_ = value;
  // @@protoc_insertion_point(field_set:Collector.Cell.cols)
}

// repeated double data = 4 [packed = true];
inline int Cell::data_size() const {
  return data_.size();
}
inline void Cell::clear_data() {
  data_.Clear();
}
inline double Cell::data(int index) const {
  // @@protoc_insertion_point(field_get:Collector.Cell.data)
  return data_.Get(index);
}
inline void Cell::set_data(int index, double value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:Collector.Cell.data)
}
inline void Cell::add_data(double value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:Collector.Cell.data)
}
inline const ::google::protobuf::RepeatedField< double >&
Cell::data() const {
  // @@protoc_insertion_point(field_list:Collector.Cell.data)
  return data_;
}
inline ::google::protobuf::RepeatedField< double >*
Cell::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Collector.Cell.data)
  return &data_;
}

// repeated string output = 1;
inline int Cell::output_size() const {
  return output_.size();
}
inline void Cell::clear_output() {
  output_.Clear();
}
inline const ::std::string& Cell::output(int index) const {
  // @@protoc_insertion_point(field_get:Collector.Cell.output)
  return output_.Get(index);
}
inline ::std::string* Cell::mutable_output(int index) {
  // @@protoc_insertion_point(field_mutable:Collector.Cell.output)
  return output_.Mutable(index);
}
inline void Cell::set_output(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Collector.Cell.output)
  output_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void Cell::set_output(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Collector.Cell.output)
  output_.Mutable(index)->assign(std::move(value));
}
#endif
inline void Cell::set_output(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  output_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Collector.Cell.output)
}
inline void Cell::set_output(int index, const char* value, size_t size) {
  output_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Collector.Cell.output)
}
inline ::std::string* Cell::add_output() {
  // @@protoc_insertion_point(field_add_mutable:Collector.Cell.output)
  return output_.Add();
}
inline void Cell::add_output(const ::std::string& value) {
  output_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Collector.Cell.output)
}
#if LANG_CXX11
inline void Cell::add_output(::std::string&& value) {
  output_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Collector.Cell.output)
}
#endif
inline void Cell::add_output(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  output_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Collector.Cell.output)
}
inline void Cell::add_output(const char* value, size_t size) {
  output_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Collector.Cell.output)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Cell::output() const {
  // @@protoc_insertion_point(field_list:Collector.Cell.output)
  return output_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Cell::mutable_output() {
  // @@protoc_insertion_point(field_mutable_list:Collector.Cell.output)
  return &output_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace Collector

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_map_2eproto__INCLUDED
