// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "map.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Detection {
class FlowStatsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<FlowStats> {
} _FlowStats_default_instance_;
class FlowKeyValueDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<FlowKeyValue> {
} _FlowKeyValue_default_instance_;
class IpRangeDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<IpRange> {
} _IpRange_default_instance_;
class CellDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Cell> {
} _Cell_default_instance_;

namespace protobuf_map_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlowStats, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlowStats, entry_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlowStats, time_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlowKeyValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlowKeyValue, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FlowKeyValue, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IpRange, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IpRange, min_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IpRange, max_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, cols_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, bytes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, pkts_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cell, output_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(FlowStats)},
  { 7, -1, sizeof(FlowKeyValue)},
  { 14, -1, sizeof(IpRange)},
  { 21, -1, sizeof(Cell)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_FlowStats_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_FlowKeyValue_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_IpRange_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Cell_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "map.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _FlowStats_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _FlowKeyValue_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _IpRange_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _Cell_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _FlowStats_default_instance_.DefaultConstruct();
  _FlowKeyValue_default_instance_.DefaultConstruct();
  _IpRange_default_instance_.DefaultConstruct();
  _Cell_default_instance_.DefaultConstruct();
  _FlowKeyValue_default_instance_.get_mutable()->key_ = const_cast< ::Detection::IpRange*>(
      ::Detection::IpRange::internal_default_instance());
  _FlowKeyValue_default_instance_.get_mutable()->value_ = const_cast< ::Detection::Cell*>(
      ::Detection::Cell::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\tmap.proto\022\tDetection\"A\n\tFlowStats\022&\n\005e"
      "ntry\030\001 \003(\0132\027.Detection.FlowKeyValue\022\014\n\004t"
      "ime\030\002 \001(\001\"O\n\014FlowKeyValue\022\037\n\003key\030\001 \001(\0132\022"
      ".Detection.IpRange\022\036\n\005value\030\002 \001(\0132\017.Dete"
      "ction.Cell\"#\n\007IpRange\022\013\n\003min\030\001 \001(\r\022\013\n\003ma"
      "x\030\002 \001(\r\"I\n\004Cell\022\014\n\004cols\030\003 \001(\005\022\021\n\005bytes\030\004"
      " \003(\001B\002\020\001\022\020\n\004pkts\030\005 \003(\001B\002\020\001\022\016\n\006output\030\001 \001"
      "(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 290);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "map.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_map_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FlowStats::kEntryFieldNumber;
const int FlowStats::kTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FlowStats::FlowStats()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_map_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detection.FlowStats)
}
FlowStats::FlowStats(const FlowStats& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      entry_(from.entry_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  time_ = from.time_;
  // @@protoc_insertion_point(copy_constructor:Detection.FlowStats)
}

void FlowStats::SharedCtor() {
  time_ = 0;
  _cached_size_ = 0;
}

FlowStats::~FlowStats() {
  // @@protoc_insertion_point(destructor:Detection.FlowStats)
  SharedDtor();
}

void FlowStats::SharedDtor() {
}

void FlowStats::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FlowStats::descriptor() {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FlowStats& FlowStats::default_instance() {
  protobuf_map_2eproto::InitDefaults();
  return *internal_default_instance();
}

FlowStats* FlowStats::New(::google::protobuf::Arena* arena) const {
  FlowStats* n = new FlowStats;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FlowStats::Clear() {
// @@protoc_insertion_point(message_clear_start:Detection.FlowStats)
  entry_.Clear();
  time_ = 0;
}

bool FlowStats::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detection.FlowStats)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Detection.FlowKeyValue entry = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_entry()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double time = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detection.FlowStats)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detection.FlowStats)
  return false;
#undef DO_
}

void FlowStats::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detection.FlowStats)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Detection.FlowKeyValue entry = 1;
  for (unsigned int i = 0, n = this->entry_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->entry(i), output);
  }

  // double time = 2;
  if (this->time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->time(), output);
  }

  // @@protoc_insertion_point(serialize_end:Detection.FlowStats)
}

::google::protobuf::uint8* FlowStats::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Detection.FlowStats)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Detection.FlowKeyValue entry = 1;
  for (unsigned int i = 0, n = this->entry_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->entry(i), deterministic, target);
  }

  // double time = 2;
  if (this->time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->time(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Detection.FlowStats)
  return target;
}

size_t FlowStats::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detection.FlowStats)
  size_t total_size = 0;

  // repeated .Detection.FlowKeyValue entry = 1;
  {
    unsigned int count = this->entry_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->entry(i));
    }
  }

  // double time = 2;
  if (this->time() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FlowStats::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detection.FlowStats)
  GOOGLE_DCHECK_NE(&from, this);
  const FlowStats* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FlowStats>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detection.FlowStats)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detection.FlowStats)
    MergeFrom(*source);
  }
}

void FlowStats::MergeFrom(const FlowStats& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detection.FlowStats)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  entry_.MergeFrom(from.entry_);
  if (from.time() != 0) {
    set_time(from.time());
  }
}

void FlowStats::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detection.FlowStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlowStats::CopyFrom(const FlowStats& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detection.FlowStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlowStats::IsInitialized() const {
  return true;
}

void FlowStats::Swap(FlowStats* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FlowStats::InternalSwap(FlowStats* other) {
  entry_.InternalSwap(&other->entry_);
  std::swap(time_, other->time_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FlowStats::GetMetadata() const {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FlowStats

// repeated .Detection.FlowKeyValue entry = 1;
int FlowStats::entry_size() const {
  return entry_.size();
}
void FlowStats::clear_entry() {
  entry_.Clear();
}
const ::Detection::FlowKeyValue& FlowStats::entry(int index) const {
  // @@protoc_insertion_point(field_get:Detection.FlowStats.entry)
  return entry_.Get(index);
}
::Detection::FlowKeyValue* FlowStats::mutable_entry(int index) {
  // @@protoc_insertion_point(field_mutable:Detection.FlowStats.entry)
  return entry_.Mutable(index);
}
::Detection::FlowKeyValue* FlowStats::add_entry() {
  // @@protoc_insertion_point(field_add:Detection.FlowStats.entry)
  return entry_.Add();
}
::google::protobuf::RepeatedPtrField< ::Detection::FlowKeyValue >*
FlowStats::mutable_entry() {
  // @@protoc_insertion_point(field_mutable_list:Detection.FlowStats.entry)
  return &entry_;
}
const ::google::protobuf::RepeatedPtrField< ::Detection::FlowKeyValue >&
FlowStats::entry() const {
  // @@protoc_insertion_point(field_list:Detection.FlowStats.entry)
  return entry_;
}

// double time = 2;
void FlowStats::clear_time() {
  time_ = 0;
}
double FlowStats::time() const {
  // @@protoc_insertion_point(field_get:Detection.FlowStats.time)
  return time_;
}
void FlowStats::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:Detection.FlowStats.time)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FlowKeyValue::kKeyFieldNumber;
const int FlowKeyValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FlowKeyValue::FlowKeyValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_map_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detection.FlowKeyValue)
}
FlowKeyValue::FlowKeyValue(const FlowKeyValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_key()) {
    key_ = new ::Detection::IpRange(*from.key_);
  } else {
    key_ = NULL;
  }
  if (from.has_value()) {
    value_ = new ::Detection::Cell(*from.value_);
  } else {
    value_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:Detection.FlowKeyValue)
}

void FlowKeyValue::SharedCtor() {
  ::memset(&key_, 0, reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&key_) + sizeof(value_));
  _cached_size_ = 0;
}

FlowKeyValue::~FlowKeyValue() {
  // @@protoc_insertion_point(destructor:Detection.FlowKeyValue)
  SharedDtor();
}

void FlowKeyValue::SharedDtor() {
  if (this != internal_default_instance()) {
    delete key_;
  }
  if (this != internal_default_instance()) {
    delete value_;
  }
}

void FlowKeyValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FlowKeyValue::descriptor() {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FlowKeyValue& FlowKeyValue::default_instance() {
  protobuf_map_2eproto::InitDefaults();
  return *internal_default_instance();
}

FlowKeyValue* FlowKeyValue::New(::google::protobuf::Arena* arena) const {
  FlowKeyValue* n = new FlowKeyValue;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FlowKeyValue::Clear() {
// @@protoc_insertion_point(message_clear_start:Detection.FlowKeyValue)
  if (GetArenaNoVirtual() == NULL && key_ != NULL) {
    delete key_;
  }
  key_ = NULL;
  if (GetArenaNoVirtual() == NULL && value_ != NULL) {
    delete value_;
  }
  value_ = NULL;
}

bool FlowKeyValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detection.FlowKeyValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Detection.IpRange key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_key()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Detection.Cell value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detection.FlowKeyValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detection.FlowKeyValue)
  return false;
#undef DO_
}

void FlowKeyValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detection.FlowKeyValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Detection.IpRange key = 1;
  if (this->has_key()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->key_, output);
  }

  // .Detection.Cell value = 2;
  if (this->has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->value_, output);
  }

  // @@protoc_insertion_point(serialize_end:Detection.FlowKeyValue)
}

::google::protobuf::uint8* FlowKeyValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Detection.FlowKeyValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Detection.IpRange key = 1;
  if (this->has_key()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->key_, deterministic, target);
  }

  // .Detection.Cell value = 2;
  if (this->has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->value_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Detection.FlowKeyValue)
  return target;
}

size_t FlowKeyValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detection.FlowKeyValue)
  size_t total_size = 0;

  // .Detection.IpRange key = 1;
  if (this->has_key()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->key_);
  }

  // .Detection.Cell value = 2;
  if (this->has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->value_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FlowKeyValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detection.FlowKeyValue)
  GOOGLE_DCHECK_NE(&from, this);
  const FlowKeyValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FlowKeyValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detection.FlowKeyValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detection.FlowKeyValue)
    MergeFrom(*source);
  }
}

void FlowKeyValue::MergeFrom(const FlowKeyValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detection.FlowKeyValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_key()) {
    mutable_key()->::Detection::IpRange::MergeFrom(from.key());
  }
  if (from.has_value()) {
    mutable_value()->::Detection::Cell::MergeFrom(from.value());
  }
}

void FlowKeyValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detection.FlowKeyValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlowKeyValue::CopyFrom(const FlowKeyValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detection.FlowKeyValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlowKeyValue::IsInitialized() const {
  return true;
}

void FlowKeyValue::Swap(FlowKeyValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FlowKeyValue::InternalSwap(FlowKeyValue* other) {
  std::swap(key_, other->key_);
  std::swap(value_, other->value_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FlowKeyValue::GetMetadata() const {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FlowKeyValue

// .Detection.IpRange key = 1;
bool FlowKeyValue::has_key() const {
  return this != internal_default_instance() && key_ != NULL;
}
void FlowKeyValue::clear_key() {
  if (GetArenaNoVirtual() == NULL && key_ != NULL) delete key_;
  key_ = NULL;
}
const ::Detection::IpRange& FlowKeyValue::key() const {
  // @@protoc_insertion_point(field_get:Detection.FlowKeyValue.key)
  return key_ != NULL ? *key_
                         : *::Detection::IpRange::internal_default_instance();
}
::Detection::IpRange* FlowKeyValue::mutable_key() {
  
  if (key_ == NULL) {
    key_ = new ::Detection::IpRange;
  }
  // @@protoc_insertion_point(field_mutable:Detection.FlowKeyValue.key)
  return key_;
}
::Detection::IpRange* FlowKeyValue::release_key() {
  // @@protoc_insertion_point(field_release:Detection.FlowKeyValue.key)
  
  ::Detection::IpRange* temp = key_;
  key_ = NULL;
  return temp;
}
void FlowKeyValue::set_allocated_key(::Detection::IpRange* key) {
  delete key_;
  key_ = key;
  if (key) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Detection.FlowKeyValue.key)
}

// .Detection.Cell value = 2;
bool FlowKeyValue::has_value() const {
  return this != internal_default_instance() && value_ != NULL;
}
void FlowKeyValue::clear_value() {
  if (GetArenaNoVirtual() == NULL && value_ != NULL) delete value_;
  value_ = NULL;
}
const ::Detection::Cell& FlowKeyValue::value() const {
  // @@protoc_insertion_point(field_get:Detection.FlowKeyValue.value)
  return value_ != NULL ? *value_
                         : *::Detection::Cell::internal_default_instance();
}
::Detection::Cell* FlowKeyValue::mutable_value() {
  
  if (value_ == NULL) {
    value_ = new ::Detection::Cell;
  }
  // @@protoc_insertion_point(field_mutable:Detection.FlowKeyValue.value)
  return value_;
}
::Detection::Cell* FlowKeyValue::release_value() {
  // @@protoc_insertion_point(field_release:Detection.FlowKeyValue.value)
  
  ::Detection::Cell* temp = value_;
  value_ = NULL;
  return temp;
}
void FlowKeyValue::set_allocated_value(::Detection::Cell* value) {
  delete value_;
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Detection.FlowKeyValue.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IpRange::kMinFieldNumber;
const int IpRange::kMaxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IpRange::IpRange()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_map_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detection.IpRange)
}
IpRange::IpRange(const IpRange& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&min_, &from.min_,
    reinterpret_cast<char*>(&max_) -
    reinterpret_cast<char*>(&min_) + sizeof(max_));
  // @@protoc_insertion_point(copy_constructor:Detection.IpRange)
}

void IpRange::SharedCtor() {
  ::memset(&min_, 0, reinterpret_cast<char*>(&max_) -
    reinterpret_cast<char*>(&min_) + sizeof(max_));
  _cached_size_ = 0;
}

IpRange::~IpRange() {
  // @@protoc_insertion_point(destructor:Detection.IpRange)
  SharedDtor();
}

void IpRange::SharedDtor() {
}

void IpRange::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* IpRange::descriptor() {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const IpRange& IpRange::default_instance() {
  protobuf_map_2eproto::InitDefaults();
  return *internal_default_instance();
}

IpRange* IpRange::New(::google::protobuf::Arena* arena) const {
  IpRange* n = new IpRange;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void IpRange::Clear() {
// @@protoc_insertion_point(message_clear_start:Detection.IpRange)
  ::memset(&min_, 0, reinterpret_cast<char*>(&max_) -
    reinterpret_cast<char*>(&min_) + sizeof(max_));
}

bool IpRange::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detection.IpRange)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 min = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &min_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 max = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &max_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detection.IpRange)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detection.IpRange)
  return false;
#undef DO_
}

void IpRange::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detection.IpRange)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 min = 1;
  if (this->min() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->min(), output);
  }

  // uint32 max = 2;
  if (this->max() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->max(), output);
  }

  // @@protoc_insertion_point(serialize_end:Detection.IpRange)
}

::google::protobuf::uint8* IpRange::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Detection.IpRange)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 min = 1;
  if (this->min() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->min(), target);
  }

  // uint32 max = 2;
  if (this->max() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->max(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Detection.IpRange)
  return target;
}

size_t IpRange::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detection.IpRange)
  size_t total_size = 0;

  // uint32 min = 1;
  if (this->min() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->min());
  }

  // uint32 max = 2;
  if (this->max() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->max());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void IpRange::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detection.IpRange)
  GOOGLE_DCHECK_NE(&from, this);
  const IpRange* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const IpRange>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detection.IpRange)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detection.IpRange)
    MergeFrom(*source);
  }
}

void IpRange::MergeFrom(const IpRange& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detection.IpRange)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.min() != 0) {
    set_min(from.min());
  }
  if (from.max() != 0) {
    set_max(from.max());
  }
}

void IpRange::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detection.IpRange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IpRange::CopyFrom(const IpRange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detection.IpRange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IpRange::IsInitialized() const {
  return true;
}

void IpRange::Swap(IpRange* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IpRange::InternalSwap(IpRange* other) {
  std::swap(min_, other->min_);
  std::swap(max_, other->max_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata IpRange::GetMetadata() const {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// IpRange

// uint32 min = 1;
void IpRange::clear_min() {
  min_ = 0u;
}
::google::protobuf::uint32 IpRange::min() const {
  // @@protoc_insertion_point(field_get:Detection.IpRange.min)
  return min_;
}
void IpRange::set_min(::google::protobuf::uint32 value) {
  
  min_ = value;
  // @@protoc_insertion_point(field_set:Detection.IpRange.min)
}

// uint32 max = 2;
void IpRange::clear_max() {
  max_ = 0u;
}
::google::protobuf::uint32 IpRange::max() const {
  // @@protoc_insertion_point(field_get:Detection.IpRange.max)
  return max_;
}
void IpRange::set_max(::google::protobuf::uint32 value) {
  
  max_ = value;
  // @@protoc_insertion_point(field_set:Detection.IpRange.max)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Cell::kColsFieldNumber;
const int Cell::kBytesFieldNumber;
const int Cell::kPktsFieldNumber;
const int Cell::kOutputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Cell::Cell()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_map_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Detection.Cell)
}
Cell::Cell(const Cell& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      bytes_(from.bytes_),
      pkts_(from.pkts_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  output_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.output().size() > 0) {
    output_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.output_);
  }
  cols_ = from.cols_;
  // @@protoc_insertion_point(copy_constructor:Detection.Cell)
}

void Cell::SharedCtor() {
  output_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cols_ = 0;
  _cached_size_ = 0;
}

Cell::~Cell() {
  // @@protoc_insertion_point(destructor:Detection.Cell)
  SharedDtor();
}

void Cell::SharedDtor() {
  output_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Cell::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Cell::descriptor() {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Cell& Cell::default_instance() {
  protobuf_map_2eproto::InitDefaults();
  return *internal_default_instance();
}

Cell* Cell::New(::google::protobuf::Arena* arena) const {
  Cell* n = new Cell;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Cell::Clear() {
// @@protoc_insertion_point(message_clear_start:Detection.Cell)
  bytes_.Clear();
  pkts_.Clear();
  output_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cols_ = 0;
}

bool Cell::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Detection.Cell)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string output = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_output()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->output().data(), this->output().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Detection.Cell.output"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 cols = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cols_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double bytes = 4 [packed = true];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_bytes())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(33u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 34u, input, this->mutable_bytes())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double pkts = 5 [packed = true];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_pkts())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) ==
                   static_cast< ::google::protobuf::uint8>(41u)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 42u, input, this->mutable_pkts())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Detection.Cell)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Detection.Cell)
  return false;
#undef DO_
}

void Cell::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Detection.Cell)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string output = 1;
  if (this->output().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->output().data(), this->output().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Detection.Cell.output");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->output(), output);
  }

  // int32 cols = 3;
  if (this->cols() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->cols(), output);
  }

  // repeated double bytes = 4 [packed = true];
  if (this->bytes_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_bytes_cached_byte_size_);
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->bytes().data(), this->bytes_size(), output);
  }

  // repeated double pkts = 5 [packed = true];
  if (this->pkts_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_pkts_cached_byte_size_);
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->pkts().data(), this->pkts_size(), output);
  }

  // @@protoc_insertion_point(serialize_end:Detection.Cell)
}

::google::protobuf::uint8* Cell::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Detection.Cell)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string output = 1;
  if (this->output().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->output().data(), this->output().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Detection.Cell.output");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->output(), target);
  }

  // int32 cols = 3;
  if (this->cols() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->cols(), target);
  }

  // repeated double bytes = 4 [packed = true];
  if (this->bytes_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _bytes_cached_byte_size_, target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->bytes_, target);
  }

  // repeated double pkts = 5 [packed = true];
  if (this->pkts_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _pkts_cached_byte_size_, target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->pkts_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Detection.Cell)
  return target;
}

size_t Cell::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Detection.Cell)
  size_t total_size = 0;

  // repeated double bytes = 4 [packed = true];
  {
    unsigned int count = this->bytes_size();
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _bytes_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated double pkts = 5 [packed = true];
  {
    unsigned int count = this->pkts_size();
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _pkts_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string output = 1;
  if (this->output().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->output());
  }

  // int32 cols = 3;
  if (this->cols() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cols());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Cell::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Detection.Cell)
  GOOGLE_DCHECK_NE(&from, this);
  const Cell* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Cell>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Detection.Cell)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Detection.Cell)
    MergeFrom(*source);
  }
}

void Cell::MergeFrom(const Cell& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Detection.Cell)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bytes_.MergeFrom(from.bytes_);
  pkts_.MergeFrom(from.pkts_);
  if (from.output().size() > 0) {

    output_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.output_);
  }
  if (from.cols() != 0) {
    set_cols(from.cols());
  }
}

void Cell::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Detection.Cell)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Cell::CopyFrom(const Cell& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Detection.Cell)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Cell::IsInitialized() const {
  return true;
}

void Cell::Swap(Cell* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Cell::InternalSwap(Cell* other) {
  bytes_.InternalSwap(&other->bytes_);
  pkts_.InternalSwap(&other->pkts_);
  output_.Swap(&other->output_);
  std::swap(cols_, other->cols_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Cell::GetMetadata() const {
  protobuf_map_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_map_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Cell

// int32 cols = 3;
void Cell::clear_cols() {
  cols_ = 0;
}
::google::protobuf::int32 Cell::cols() const {
  // @@protoc_insertion_point(field_get:Detection.Cell.cols)
  return cols_;
}
void Cell::set_cols(::google::protobuf::int32 value) {
  
  cols_ = value;
  // @@protoc_insertion_point(field_set:Detection.Cell.cols)
}

// repeated double bytes = 4 [packed = true];
int Cell::bytes_size() const {
  return bytes_.size();
}
void Cell::clear_bytes() {
  bytes_.Clear();
}
double Cell::bytes(int index) const {
  // @@protoc_insertion_point(field_get:Detection.Cell.bytes)
  return bytes_.Get(index);
}
void Cell::set_bytes(int index, double value) {
  bytes_.Set(index, value);
  // @@protoc_insertion_point(field_set:Detection.Cell.bytes)
}
void Cell::add_bytes(double value) {
  bytes_.Add(value);
  // @@protoc_insertion_point(field_add:Detection.Cell.bytes)
}
const ::google::protobuf::RepeatedField< double >&
Cell::bytes() const {
  // @@protoc_insertion_point(field_list:Detection.Cell.bytes)
  return bytes_;
}
::google::protobuf::RepeatedField< double >*
Cell::mutable_bytes() {
  // @@protoc_insertion_point(field_mutable_list:Detection.Cell.bytes)
  return &bytes_;
}

// repeated double pkts = 5 [packed = true];
int Cell::pkts_size() const {
  return pkts_.size();
}
void Cell::clear_pkts() {
  pkts_.Clear();
}
double Cell::pkts(int index) const {
  // @@protoc_insertion_point(field_get:Detection.Cell.pkts)
  return pkts_.Get(index);
}
void Cell::set_pkts(int index, double value) {
  pkts_.Set(index, value);
  // @@protoc_insertion_point(field_set:Detection.Cell.pkts)
}
void Cell::add_pkts(double value) {
  pkts_.Add(value);
  // @@protoc_insertion_point(field_add:Detection.Cell.pkts)
}
const ::google::protobuf::RepeatedField< double >&
Cell::pkts() const {
  // @@protoc_insertion_point(field_list:Detection.Cell.pkts)
  return pkts_;
}
::google::protobuf::RepeatedField< double >*
Cell::mutable_pkts() {
  // @@protoc_insertion_point(field_mutable_list:Detection.Cell.pkts)
  return &pkts_;
}

// string output = 1;
void Cell::clear_output() {
  output_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Cell::output() const {
  // @@protoc_insertion_point(field_get:Detection.Cell.output)
  return output_.GetNoArena();
}
void Cell::set_output(const ::std::string& value) {
  
  output_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Detection.Cell.output)
}
#if LANG_CXX11
void Cell::set_output(::std::string&& value) {
  
  output_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Detection.Cell.output)
}
#endif
void Cell::set_output(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  output_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Detection.Cell.output)
}
void Cell::set_output(const char* value, size_t size) {
  
  output_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Detection.Cell.output)
}
::std::string* Cell::mutable_output() {
  
  // @@protoc_insertion_point(field_mutable:Detection.Cell.output)
  return output_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Cell::release_output() {
  // @@protoc_insertion_point(field_release:Detection.Cell.output)
  
  return output_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Cell::set_allocated_output(::std::string* output) {
  if (output != NULL) {
    
  } else {
    
  }
  output_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), output);
  // @@protoc_insertion_point(field_set_allocated:Detection.Cell.output)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Detection

// @@protoc_insertion_point(global_scope)
